var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var boo;
var strNumTuple;
myString = 'helllo '.slice(0, 3);
myNum = 22;
myBool = false;
myVar = true;
strArr = ['hello', 'worldy', 'hen'];
numArr = [1, 5, 6];
boo = [true, false];
strNumTuple = ['hello', 1];
var myVoid = null;
console.log(boo);
